### ISSUE TITLE
libyang issue with arguments that are swapped

### ISSUE THREAD

**Issue by ericjmonson** [ygorelik/ydk-gen#15]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Current Behavior
I don't see a way to submit an issue against the forked version of libyang ... however, there is a bug that is causing a segfault in my application.

https://github.com/ygorelik/libyang/blob/master/src/xpath.c#L2991

The function call has the 1st and 2nd arguments swapped. The original code looks like this:
```
LOGWRN("Argument #%u of %s is node \"%s\", not of string-type.", __func__, i + 1, sleaf->name);
```

The correct code should look like this:
```
LOGWRN("Argument #%u of %s is node \"%s\", not of string-type.", i + 1, __func__, sleaf->name);
```

**Comment by ygorelik** [comment]
I moved your issue to [CiscoDevNet](https://github.com/CiscoDevNet/ydk-gen/issues/1081) repository. Please use that repository for any future found issues.
